### ISSUE TITLE
Building 2+ packages at once

### ISSUE THREAD

**Issue by jamesbraza** [hynek/build-and-inspect-python-package#146]
I have something like [this workspace layout](https://docs.astral.sh/uv/concepts/workspaces/#workspace-layouts), which leads to this GitHub Action:

```yaml
      - run: |-
          uv build --sdist --wheel --out-dir dist/ .
          uv build --sdist --wheel --out-dir dist/ packages/seeds
          uv build --sdist --wheel --out-dir dist/ packages/bird-feeder
```

Looking at version `2.9.0`'s inputs: https://github.com/hynek/build-and-inspect-python-package/blob/v2.9.0/action.yml#L9-L25

Is the correct way to handle this to invoke `build-and-inspect-python-package` three times, with a different `upload-name-suffix` each time?

**Comment by hynek** [comment]
Hmm this is virgin soil here. :) I have never used such a setup, so I have to guess a bit, but I would say: cd in to those packages and add a suffix, yes. Please let me know how it goes, so we can add something to the docs.

**Comment by jamesbraza** [comment]
I have something like this:

```yaml
      - name: Check albatross build
        uses: hynek/build-and-inspect-python-package@v2
        with:
          upload-name-suffix: -albatross
      - name: Check bird-feeder build
        uses: hynek/build-and-inspect-python-package@v2
        with:
          path: packages/bird-feeder
          upload-name-suffix: -bird-feeder
      - name: Check seeds build
        uses: hynek/build-and-inspect-python-package@v2
        with:
          path: packages/seeds
          upload-name-suffix: -seeds
```

And it leads to this summary:

![screenshot of summary](https://github.com/user-attachments/assets/2605f115-7fdb-4e62-beec-e566feac29f1)

We should put the `upload-name-suffix` into the summary title, so everything doesn't say `Package Contents`, it can say `Package-albatross Contents` (and be distinguishable)
