### ISSUE TITLE
Default artifact name is incompatible with `strategy` matrix

### ISSUE THREAD

**Issue by jamesbraza** [hynek/build-and-inspect-python-package#148]
As of version 2.9.0, let's say one has something like this:

```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12] # Min and max supported Python versions
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2
```

Whichever workflow happens to run `hynek/build-and-inspect-python-package` second will fail on the `actions/upload-artifact` step at https://github.com/hynek/build-and-inspect-python-package/blob/v2.9.0/action.yml#L149-L153 because:
1. First workflow made a `Packages` artifact
2. Second workflow has a name collision on `Packages`

What do you think of changing the default behavior to work with `strategy` matrixes?

**Comment by jamesbraza** [comment]
The workaround is to use the `strategy` matrix's value as the suffix:

```yaml
    strategy:
      matrix:
        python-version: [3.11, 3.12] # Min and max supported Python versions
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2
        with:
          upload-name-suffix: -${{ matrix.python-version }}
```
