### ISSUE TITLE
Wheel is built for previous tag

### ISSUE THREAD

**Issue by jacob-mannhardt** [hynek/build-and-inspect-python-package#153]
Many thanks for this fantastic action!
When building the package with `hynek/build-and-inspect-python-package@v2`, the wheel is built for the previous tag, not the newly created tag. Let's say the new tag is v2.0.0 and the previous one was v1.9.8, then the wheel is built for v1.9.8. Consequently, v2.0.0 is not available on PyPI. Do you know why that happens?

My workflow is the following:

1. Run some tests `build`
2. Bump version with  `jasonamyers/github-bumpversion-action@v1.0.5`
3. Create Github release if minor or major bump
4. Build package
5. Distribute to TestPyPI and PyPI

Please find the relevant workflow snippet below. I have omitted the test procedure.

```yaml
bump_version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Bump version and push tag
        uses: jasonamyers/github-bumpversion-action@v1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        if: env.bump != 'none'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

  release:
    name: "Create Github Release"
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract tag version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Check for major/minor version
        id: check_version
        run: |
          TAG=${{ steps.get-latest-tag.outputs.tag }}
          PATCH_VERSION=$(echo $TAG | cut -d. -f3)
          echo "tag=$TAG"
          echo "patch=$PATCH_VERSION"
          echo "patch=$PATCH_VERSION" >> $GITHUB_ENV
  
          if [[ $PATCH_VERSION -eq 0 ]]; then
            echo "is_major_minor=true" >> $GITHUB_ENV
          else
            echo "is_major_minor=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        if: env.is_major_minor == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
          release_name: Release ${{ steps.get-latest-tag.outputs.tag }}
          body: "Automated release for version ${{ steps.get-latest-tag.outputs.tag }} after major/minor version bump."
          draft: false
          prerelease: false

  build-package:
    name: "Build and verify package"
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2

  release-test-pypi:
    name: "Release to Test PyPI"
    runs-on: ubuntu-latest
    needs: build-package
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/XXXXXX/
    permissions:
      id-token: write
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  release-pypi:
    name: "Release to PyPI"
    runs-on: ubuntu-latest
    needs: build-package
    environment:
      name: pypi
      url: https://pypi.org/project/XXXXXX/
    permissions:
      id-token: write
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```

**Comment by hynek** [comment]
So the thing is: baipp doesn't build your package, `uv build` does. So if `uv build` does locally the correct thing, there is some bug in the interaction between the other actions. Particularly, it looks like the checkout is not receiving the result of the `github-push-action` action? I guess the best way would be to add some debugging steps running `git tag -l`

**Comment by jacob-mannhardt** [comment]
Many thanks for your response, Hynek!

Just to make sure I understood your suggestion correctly (I'm just getting started with Github Actions): would you add the debugging step `HERE`?

```
build-package:
    name: "Build and verify package"
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - HERE
      - uses: hynek/build-and-inspect-python-package@v2
```

Do you think it makes sense to specify the `tag` as the `ref` argument in the `actions/checkout@v4` step, because I have set the correct `tag` in `steps.get-latest-tag.outputs.tag`

Many thanks for your support!

**Comment by webknjaz** [comment]
@jacob-mannhardt one of your jobs modifies Git and you seem to expect that the following one would fetch the new commit of the Git repo. However, the entire workflow run is triggered with the same context and the checkout action will use that same commit that is coming from the context in the internal variables of GitHub. If you want to do such things, you have to save that commit/tag as job outputs and then pass it around everywhere in the following jobs. So yes, you have to specify `ref:`, otherwise, `actions/checkout` will keep using its logic that only depends on the event that triggered the workflow run.

**Comment by jacob-mannhardt** [comment]
Thank you both for your help! Unfortunately, it does not work to specify the tag. I've now added the `ref:` argument

```
  build-package:
    name: "Build and verify package"
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-latest-tag.outputs.tag }}
      - uses: hynek/build-and-inspect-python-package@v2
```

but it still uses the previous tag. `steps.get-latest-tag.outputs.tag` is the new tag, i.e., the most recent tag.

**Comment by webknjaz** [comment]
@jacob-mannhardt you're passing in an empty string. There's no step with such ID in that job. This causes the default discovery behavior being hit.

**Comment by jacob-mannhardt** [comment]
@webknjaz what do you mean? I'm defining the ID `>>>HERE<<<` (see below). And I am already using `${{ steps.get-latest-tag.outputs.tag }}` successfully in multiple steps, e.g., the Github Release. Maybe I didn't understand your point correctly.
Thank you so much for your help!

```
bump_version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Bump version and push tag
        uses: jasonamyers/github-bumpversion-action@v1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        if: env.bump != 'none'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

  release:
    name: "Create Github Release"
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract tag version
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: >>>HERE<<< get-latest-tag
        with:
          semver_only: true

      - name: Check for major/minor version
        id: check_version
        run: |
          TAG=${{ steps.get-latest-tag.outputs.tag }}
          PATCH_VERSION=$(echo $TAG | cut -d. -f3)
          echo "tag=$TAG"
          echo "patch=$PATCH_VERSION"
          echo "patch=$PATCH_VERSION" >> $GITHUB_ENV
  
          if [[ $PATCH_VERSION -eq 0 ]]; then
            echo "is_major_minor=true" >> $GITHUB_ENV
          else
            echo "is_major_minor=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        if: env.is_major_minor == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}
          release_name: Release ${{ steps.get-latest-tag.outputs.tag }}
          body: "Automated release for version ${{ steps.get-latest-tag.outputs.tag }} after major/minor version bump."
          draft: false
          prerelease: false

  build-package:
    name: "Build and verify package"
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-latest-tag.outputs.tag }}
      - uses: hynek/build-and-inspect-python-package@v2

  release-test-pypi:
    name: "Release to Test PyPI"
    runs-on: ubuntu-latest
    needs: build-package
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/XXXXXX/
    permissions:
      id-token: write
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  release-pypi:
    name: "Release to PyPI"
    runs-on: ubuntu-latest
    needs: build-package
    environment:
      name: pypi
      url: https://pypi.org/project/XXXXXX/
    permissions:
      id-token: write
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
```
