### ISSUE TITLE
add a resuable workflow that caches/builds + another one that downloads artifacts + does pypi uploads 

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [hynek/build-and-inspect-python-package#40]
with https://docs.github.com/en/actions/using-workflows/reusing-workflows
the action can be argument to enable just listing it with a basic setup

aka instead of copy&pasting

```yaml
jobs:
  check-package:
    name: Build & inspect our package.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hynek/build-and-inspect-python-package@v1
      
      
      
 ```
 and then adding loads of extra stuff,

 one would have
 
 ```
 jobs:
   check-package:
     uses: hynek/build-and-inspect-python-package/.github/workflow/build-and-inspectyamö
     with:
        fetch-depth: 0
        hide-local-version: true
   test:
       strategy:
         matrix:
            $python-version/runs-on-from-inspection # needs investigation
       needs:  check-package
       steps: ...
       
       
 pypi-uploads:
    uses:  hynek/build-and-inspect-python-package/.github/workflow/upload-pypi-or-testpypi.yaml
       
 ```
